export const ITEMS: string[] = [
    'Ciabbatte Rolls',
    'Sourdough Bread',
    'Whole Wheat Bread',
    'Whole Milk',
    '2% Milk',
    'Fat-Free Milk',
    'Half & Half',
    'Heavy Whip',
    'Almond Milk',
    'Soy Milk',
    'Coconut Milk',
    'Oat Milk',
    'Eggnog',
    'Strawberry & Cream Cheese Turnover',
    'Peach & Cream Cheese Turnover',
    'Cream Cheese Turnover',
    'Chocolate Chip Muffin',
    'Pecan Cranberry Muffin',
    'Blueberry Muffin',
    'Poppy Seed Muffin',
    'Bran Muffin',
    'Croissant',
    'Chocolate Croissant',
    'Sesame Bagel',
    'Plain Bagel',
    'Cheese Bagel',
    'Chocolate Chip Cookie',
    'Zu Zus',
    "Dad's Delight",
    'Napoleon',
    'Cannoli',
    'Macaroon',
    'Fruit Tart',
    'Carrot Cake',
    'Apple Strudel',
    'Salted Caramel Cupcake',
    'Lemon Gold Cupcake',
    'Seasonal Cupcake',
    'Strawberry Whip Cream Cake',
    'Strawberry Whip Cream Cake (Quarter)',
    'Espresso Ganache',
    'Espresso Ganache (Quarter)',
    'Rasberry Espresso Ganache',
    'Rasberry Espresso Ganache (Quarter)',
    'Ava Chocolate Fudge',
    'Ava Chocolate Fudge (Quarter)',
    'Everything Bagel',
];

export const UNITS: string[] = [
    '12/Pack',
    '1 Loaf',
    '1 Gal',
    '1 Qt',
    '1/2 Gal',
    '12/32 Oz',
    '1 Pc',
    '4 Pcs/Pack',
    '12 Pcs/Pack',
    '1 Cake',
    '1/4 Cake',
];

// Do NOT change order of stores below - it Must match with what app's tables use and production's stores table
export const STORES: string[] = [
    'Hall',
    'Progress',
    'Kruse',
    'Orenco',
    // 'Tigard',
];

export const INVOICE_CATEG: string[] = [
    'SANDWICH',
    'PASTRY',
    'FOOD',
    'COOLER&EXTRAS',
    'BEVERAGE',
    'MISC/BATHROOM',
    'CHOCOLATE&TEA',
    'COFFEE',
    'NONE',
];
export const STORE_CATEG: string[] = [
    'FRONT',
    'STOCKROOM',
    'FRIDGE',
    'GENERAL',
    'BEANS&TEA',
    'PASTRY',
    'NONE',
];
export const CRON_CATEG: string[] = [
    'PASTRY',
    'MILK',
    'BREAD',
    'RETAILBEANS',
    'MEATS',
    'NONE',
];
